### ISSUE TITLE
HERMES_INVOCATION: Error occurs. Error 2: Service Unavailable: Check whether you have connected Hermes.

### ISSUE THREAD

**Issue by umesh0492** [elemers/HermesEventBus#30]
It happens when main process get closed and other service is running

**Comment by Xiaofei-it** [comment]
This happens when the other service wants to use the Hermes library to access the APIs in the main process to post event but the main process has already died. This will print an error log but will not crash the app. Also, after the main process dies, the sub-processes will no longer be able to post events.

To avoid this error log, try to keep the main process alive. However, since the error does not crash your app, you can also ignore it.

**Comment by Xiaofei-it** [comment]
This happens when the other service wants to use the Hermes library to access the APIs in the main process to post event but the main process has already died. This will print an error log but will not crash the app. Also, after the main process dies, the sub-processes will no longer be able to post events.

To avoid this error log, try to keep the main process alive. However, since the error does not crash your app, you can also ignore it.

**Comment by umesh0492** [comment]
Hey @Xiaofei-it , thats ok. But I want to re-establish the connection in between the main and sub-process, when main process become alive again.

My question is how to re-establish the connection, if main process becomes alive again? So, that then start communicating with one another when main process comes alive again. 

Thanks for your prompt reply.

**Comment by umesh0492** [comment]
@Xiaofei-it waiting for your reply... Thanks:)

**Comment by umesh0492** [comment]
@Xiaofei-it waiting for your reply... Thanks:)

**Comment by sxlvalue** [comment]
The author is ill.

**Comment by Xiaofei-it** [comment]
@umesh0492 I will deal with this issue this week.

**Comment by Xiaofei-it** [comment]
@umesh0492 Sorry for keep you waiting for my reply for such a long time.

I have read the code you committed. And I have commented on it. Please reply to me and I will merge the pull request later.

**Comment by umesh0492** [comment]
@Xiaofei-it thanks for coming back online :).  That commit wasn't by me, that you referring. 

My issue is still the same :::

I want to re-establish the connection in between the main and sub-process, when main process become alive again.

My question is how to re-establish the connection, if main process becomes alive again? So, that then start communicating with one another when main process comes alive again.

Will wait for your solution to above query :).

**Comment by Xiaofei-it** [comment]
For the time being, HermesEventBus does not support the feature you refer to.

But I will add this feature.

First, I will merge the pull request #26. And then I will modify the Hermes library, by allowing the user to provide Hermes with a callback which will be called if the exception occurs. The user can re-establish the connection in the callback.

You can provide me with more suggestions.

**Comment by umesh0492** [comment]
Hey @Xiaofei-it any updates on this issue. Thanks :)

**Comment by Xiaofei-it** [comment]
I have merged a pull request #26, which may fix this.
